name: MythicRPG
version: '${project.version}'
main: net.alterstepix.mythicrpg.MythicRPG
api-version: 1.18
authors: [ AlterStepix, Crutogurch ]
description: todo
commands:
  mythic-rpg:
    description: TODO
    usage: /<command> [option] [arguments...]